add_newline = false

format = "$directory$git_branch $character"

[username]
show_always = true
style_user = "yellow"
style_root = "red bold"

[hostname]
ssh_only = false
# style = "blue"

[directory]
truncation_length = 10
truncate_to_repo = false
style = "blue"

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[os]
style = "bold blue"
disabled = false # æ˜¾ç¤ºæ“ä½œç³»ç»Ÿå›¾æ ‡
format = "[$symbol]($style)"

[git_branch]
symbol = "ï˜ "
style = "bold green"
format = "[$symbol$branch]($style)"

[git_status]
format = '([$all_status]($style))'
style = "bold red"

[kubernetes]
symbol = "â˜¸ï¸ "
format = '[($context) \($namespace\)](dim purple) '
disabled = false

[python]
symbol = "ğŸ"
format = '[${symbol}(${version}) \($virtualenv\)](bold green) '
python_binary = "python3"

[rust]
symbol = "ğŸ¦€"
format = '[$symbol($version)](red bold) '

[golang]
symbol = "î˜§"
format = '[$symbol($version)](bold blue) '

[package]
symbol = "ğŸ“¦"
format = "[$symbol$version](208 bold) "
disabled = true

